SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS classes;
DROP TABLE IF EXISTS courses;
DROP TABLE IF EXISTS departments;
DROP TABLE IF EXISTS exam_arrangements;
DROP TABLE IF EXISTS knowledge_embedding;
DROP TABLE IF EXISTS majors;
DROP TABLE IF EXISTS scores;
DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS teachers;

SET FOREIGN_KEY_CHECKS = 1;